"""AddSplitwiseFeatures

Revision ID: 197addd7043f
Revises: 1c3596c87ac1
Create Date: 2026-03-03 13:15:19.231585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197addd7043f'
down_revision = '1c3596c87ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_splits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('split_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('receipt_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('default_currency')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('receipt_url')
        batch_op.drop_column('split_type')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')
        batch_op.drop_column('base_amount')

    with op.batch_alter_table('expense_splits', schema=None) as batch_op:
        batch_op.drop_column('percentage')
        batch_op.drop_column('share_count')

    op.drop_table('expense_comments')
    op.drop_table('expense_activities')
    # ### end Alembic commands ###
