"""fix missing pricing columns

Revision ID: 1c3596c87ac1
Revises: fb465ddbf6bb
Create Date: 2026-03-03 00:12:47.315286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3596c87ac1'
down_revision = 'fb465ddbf6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_per_person', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_per_night', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.drop_column('is_per_night')
        batch_op.drop_column('is_per_person')

    # ### end Alembic commands ###
