"""increase url lengths to 3000

Revision ID: 36d45266d1a0
Revises: c10bdb2cd9f0
Create Date: 2026-04-08 21:15:00.677643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d45266d1a0'
down_revision = 'c10bdb2cd9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=3000),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=3000),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=3000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###
