"""add price_per_day_pp to options

Revision ID: 6bcefb0f1db1
Revises: 197addd7043f
Create Date: 2026-03-07 23:23:02.319500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcefb0f1db1'
down_revision = '197addd7043f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_day_pp', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.drop_column('price_per_day_pp')

    # ### end Alembic commands ###
