"""increase google maps and receipt url lengths

Revision ID: 9694a6606099
Revises: 9a82202bd625
Create Date: 2026-04-08 20:21:40.759286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9694a6606099'
down_revision = '9a82202bd625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_activities', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1500),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('receipt_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1500),
               existing_nullable=True)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('google_maps_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.alter_column('google_maps_url',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('receipt_url',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('expense_activities', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
