"""increase link length to 1500

Revision ID: 9a82202bd625
Revises: cd4b2561fad1
Create Date: 2026-04-08 20:20:23.056022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a82202bd625'
down_revision = 'cd4b2561fad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1500),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1500),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.String(length=1500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
