"""Add total_price to stay_options

Revision ID: 9c67cd088ebe
Revises: 6bcefb0f1db1
Create Date: 2026-03-08 13:56:16.548627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c67cd088ebe'
down_revision = '6bcefb0f1db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
