"""Add status to TripMember

Revision ID: b767e506ab4a
Revises: c35beff32237
Create Date: 2026-03-01 16:24:21.961232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b767e506ab4a'
down_revision = 'c35beff32237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_members', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
