"""Add is_finalized to options and expense_date to expenses

Revision ID: c35beff32237
Revises: f09258a1d568
Create Date: 2026-03-01 14:57:33.133014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35beff32237'
down_revision = 'f09258a1d568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_date', sa.Date(), nullable=True))

    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finalized', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.drop_column('is_finalized')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('expense_date')

    # ### end Alembic commands ###
