"""add show_budget_tour to users

Revision ID: cd4b2561fad1
Revises: 
Create Date: 2026-03-29 19:15:24.898903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4b2561fad1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('show_budget_tour', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET show_budget_tour = true")
    op.alter_column('users', 'show_budget_tour', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_budget_tour')

    # ### end Alembic commands ###
