"""Add budget planner fields

Revision ID: ddf8ec6117ab
Revises: 9ac7a745fbe7
Create Date: 2026-03-18 18:17:10.434191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf8ec6117ab'
down_revision = '9ac7a745fbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('destination', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('added_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('num_travelers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_promoted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('is_promoted')
        batch_op.drop_column('num_travelers')
        batch_op.drop_column('budget')
        batch_op.drop_column('destination')

    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('duration_days')
        batch_op.drop_column('destination')
        batch_op.drop_column('is_global')

    # ### end Alembic commands ###
