"""Add new columns to stay_options table

Revision ID: f09258a1d568
Revises: 12c1d70e2020
Create Date: 2026-03-01 14:25:53.990997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09258a1d568'
down_revision = '12c1d70e2020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('link_title', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('link_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('check_out_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stay_options', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')
        batch_op.drop_column('link_description')
        batch_op.drop_column('link_title')
        batch_op.drop_column('image_url')
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
