"""Add google_maps_url to Trip

Revision ID: fb465ddbf6bb
Revises: b767e506ab4a
Create Date: 2026-03-02 22:50:49.642119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb465ddbf6bb'
down_revision = 'b767e506ab4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_maps_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('google_maps_url')

    # ### end Alembic commands ###
